volumes:
  db_volume:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - db_volume:/var/lib/postgresql/data/
  backend:
    image: fantalovsergey/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: fantalovsergey/foodgram_frontend
    volumes:
      - static:/app/result_build/
  nginx:
    image: fantalovsergey/foodgram_nginx
    ports:
      - 8800:80
    volumes:
      - static:/usr/share/nginx/html/
      - media:/usr/share/nginx/media/
    depends_on:
      - backend
