STR_MAX_LENGTH = 30
STR_MAX_LENGTH_SHORT = STR_MAX_LENGTH // 2

TAG_FIELDS_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

DIGITS_ASCII = tuple(range(48, 58))
UPPER_CASE_ASCII = tuple(range(65, 91))
LOWER_CASE_ASCII = tuple(range(97, 123))
VALID_SYMBOLS = DIGITS_ASCII + UPPER_CASE_ASCII + LOWER_CASE_ASCII

SHORT_LINK_SIGNIFICANT_LENGTH = 8
SHORT_LINK_MAX_LENGTH = 16
